[format]
line-width = 80
indent-width = 2
indent-style = "space"
line-ending = "auto"
persistent-line-breaks = false
exclude = ["dev/*", "TADAShiny.Rproj"]
default-exclude = true
skip = []
table = []
default-table = true
