utils::globalVariables(c(
  "TADA.CensoredData.Flag", "ResultIdentifier",
  "num", "Label", "TADA.ResultMeasureValue",
  "TADA.CensoredMethod", "TADA.Remove",
  "MonitoringLocationIdentifier", "MonitoringLocationName",
  "TADA.LatitudeMeasure", "TADA.LongitudeMeasure",
  "ActivityStartDate", "TADA.CharacteristicName",
  "OrganizationIdentifier", "OrganizationFormalName",
  "Result_Count", "TADA.Chars", "Step", "Count",
  "Legend", "req",
  "TADA.DetectionQuantitationLimitMeasure.MeasureValue",
  "DetectionQuantitationLimitMeasure.MeasureUnitCode",
  "TADA.ResultMeasure.MeasureUnitCode",
  "group", "groupname", "MonitoringLocationTypeName",
  "quantile", "median", "moduleServer",
  "Target.TADA.CharacteristicName",
  "Target.TADA.MethodSpecificationName",
  "write.csv", "read.csv", "downloadHandler",
  "Rank", "Target.TADA.ResultSampleFractionText"
))
