name: Scheduled Component File Update

on:
  # Daily at 2:01AM https://crontab.guru/
  schedule:
    - cron: '1 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  maintenance_updates:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo (existing branch)
        uses: actions/checkout@v5
        id: bad-checkout
        continue-on-error: true
        with:
          ref: maintenance-branch
        # If the first checkout fails, we checkout the `develop` branch by default
      - name: Fallback to default branch
        if: steps.bad-checkout.outcome == 'failure'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        
      - name: Install TADAShiny
        run: |
          install.packages("remotes")
          library(remotes)
          remotes::install_github("USEPA/TADAShiny", ref = "develop", dependencies = TRUE, force = TRUE)
        shell: Rscript {0}
        
      - name: Update WQP filter options
        run: |
          library(TADAShiny)
          url <- "https://www.waterqualitydata.us/data/Station/search?mimeType=csv&zip=no"
          response <- httr::GET(url)
          csv_content <- httr::content(response, "text")
          data <- utils::read.csv(text = csv_content, stringsAsFactors = FALSE)
          mlids <- unique(data$MonitoringLocationIdentifier)
          save(mlids, file = "inst/extdata/query_choices.Rdata")
        shell: Rscript {0}

      - name: Commit updated filter options
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: "Update WQP filter options"
          add: '[./inst/extdata/*]'
          new_branch: maintenance-branch
